### PR TITLE
fix: Select first item

### PR DESCRIPTION
**Pull request by msvticket**
You can't just press to return to select the first default option (for example **Create new application from a Quickstart** when running `jx project`). This fixes that.

Fix require upgrade of jx-helpers, so I upgrade other Jenkins X dependencies as well.

### CODE REVIEW

**Comment by msvticket** [comment]
Should I have kept the replacements?

**Review by tomhobson — CHANGES_REQUESTED** [review]
Sorry, probably my mistake, but I don't really understand. What is the first selection and why is this an improvement?

**Comment by msvticket** [comment]
> Sorry, probably my mistake, but I don't really understand. What is the first selection and why is this an improvement?

I can understand that. That's why I first asked @ankitm123 to review, since he know the issue. But then I got impatient and asked you as well...

The issue is that if you run for for example `jx project` and is met by 
```
? Which kind of project you want to create:   [Use arrows to move, type to filter]
> Create new application from a Quickstart
  Create new application from a Machine Learning Quickstart
  Create new Spring Boot microservice
  Import existing code from a directory
  Import code from a git repository
  Import code from a github repository
```

and then immediately press enter to select `Create new application from a Quickstart` the command prints this and exits:
`error: unknown selection:`

It's the upgrade of jx-helper that fixes this. But I chose to upgrade some other dependencies as well while at it.

**Comment by ankitm123** [comment]
My bad, approving!

**Review by ankitm123 — APPROVED** [review]

**Pull request merged**
